# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Altera_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1173, 531)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 771, 21))
        self.label.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(94, 94, 94);\n"
"}")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 721, 421))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.sair = QtWidgets.QPushButton(Dialog)
        self.sair.setGeometry(QtCore.QRect(10, 500, 75, 23))
        self.sair.setObjectName("sair")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(750, 60, 411, 421))
        self.frame.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 47, 21))
        self.label_2.setObjectName("label_2")
        self.nomeEdit = QtWidgets.QLineEdit(self.frame)
        self.nomeEdit.setGeometry(QtCore.QRect(76, 63, 311, 21))
        self.nomeEdit.setObjectName("nomeEdit")
        self.usuarioEdit = QtWidgets.QLineEdit(self.frame)
        self.usuarioEdit.setGeometry(QtCore.QRect(76, 112, 311, 20))
        self.usuarioEdit.setObjectName("usuarioEdit")
        self.senhaEdit = QtWidgets.QLineEdit(self.frame)
        self.senhaEdit.setGeometry(QtCore.QRect(76, 162, 311, 20))
        self.senhaEdit.setObjectName("senhaEdit")
        self.salvarEdit = QtWidgets.QPushButton(self.frame)
        self.salvarEdit.setGeometry(QtCore.QRect(320, 380, 75, 23))
        self.salvarEdit.setObjectName("salvarEdit")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 391, 20))
        self.label_5.setStyleSheet("background-color: rgb(94, 94, 94);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 61, 21))
        self.label_6.setObjectName("label_6")
        self.senhaEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.senhaEdit_2.setGeometry(QtCore.QRect(76, 212, 311, 20))
        self.senhaEdit_2.setObjectName("senhaEdit_2")
        self.senhaEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.senhaEdit_3.setGeometry(QtCore.QRect(76, 262, 311, 20))
        self.senhaEdit_3.setObjectName("senhaEdit_3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 71, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 260, 61, 21))
        self.label_8.setObjectName("label_8")
        self.limparEdit = QtWidgets.QPushButton(self.frame)
        self.limparEdit.setGeometry(QtCore.QRect(20, 380, 75, 23))
        self.limparEdit.setObjectName("limparEdit")
        self.senhaEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.senhaEdit_4.setGeometry(QtCore.QRect(110, 320, 221, 20))
        self.senhaEdit_4.setObjectName("senhaEdit_4")
        self.gerarSenha = QtWidgets.QPushButton(self.frame)
        self.gerarSenha.setGeometry(QtCore.QRect(30, 319, 75, 23))
        self.gerarSenha.setObjectName("gerarSenha")
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.label_2.raise_()
        self.nomeEdit.raise_()
        self.usuarioEdit.raise_()
        self.senhaEdit.raise_()
        self.salvarEdit.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.senhaEdit_2.raise_()
        self.senhaEdit_3.raise_()
        self.limparEdit.raise_()
        self.senhaEdit_4.raise_()
        self.gerarSenha.raise_()
        self.pesquisaEdit = QtWidgets.QLineEdit(Dialog)
        self.pesquisaEdit.setGeometry(QtCore.QRect(800, 20, 171, 23))
        self.pesquisaEdit.setObjectName("pesquisaEdit")
        self.btnPesquisaEdit = QtWidgets.QPushButton(Dialog)
        self.btnPesquisaEdit.setGeometry(QtCore.QRect(980, 20, 41, 23))
        self.btnPesquisaEdit.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    image: url(:/img/magnify.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 0, 0);\n"
"    image: url(:/img/magnify (1).png);\n"
"}")
        self.btnPesquisaEdit.setText("")
        self.btnPesquisaEdit.setObjectName("btnPesquisaEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Alterar Usuário</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome                   "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Usuario"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Senha 1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Senha 2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Senha 3"))
        self.sair.setText(_translate("Dialog", "Sair"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Nome:</span></p></body></html>"))
        self.salvarEdit.setText(_translate("Dialog", "Salvar"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Dados do Usuário</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Usuário:</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Senha 1:</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Senha 2:</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Senha 3:</span></p></body></html>"))
        self.limparEdit.setText(_translate("Dialog", "Limpar"))
        self.gerarSenha.setText(_translate("Dialog", "Gerar Senha"))
import templates.imgAltera


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
