# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastro(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 312)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 31))
        self.label.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 129, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 51, 31))
        self.label_4.setObjectName("label_4")
        self.gerarSenha = QtWidgets.QPushButton(Dialog)
        self.gerarSenha.setGeometry(QtCore.QRect(285, 188, 75, 23))
        self.gerarSenha.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gerarSenha.setObjectName("gerarSenha")
        self.senhaCad = QtWidgets.QLineEdit(Dialog)
        self.senhaCad.setEnabled(True)
        self.senhaCad.setGeometry(QtCore.QRect(71, 188, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.senhaCad.setFont(font)
        self.senhaCad.setObjectName("senhaCad")
        self.usuarioCad = QtWidgets.QLineEdit(Dialog)
        self.usuarioCad.setEnabled(True)
        self.usuarioCad.setGeometry(QtCore.QRect(82, 130, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usuarioCad.setFont(font)
        self.usuarioCad.setObjectName("usuarioCad")
        self.nome = QtWidgets.QLineEdit(Dialog)
        self.nome.setEnabled(True)
        self.nome.setGeometry(QtCore.QRect(70, 67, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nome.setFont(font)
        self.nome.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.nome.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.nome.setObjectName("nome")
        self.slavarCad = QtWidgets.QPushButton(Dialog)
        self.slavarCad.setGeometry(QtCore.QRect(310, 280, 75, 23))
        self.slavarCad.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.slavarCad.setObjectName("slavarCad")
        self.cancelarCad = QtWidgets.QPushButton(Dialog)
        self.cancelarCad.setGeometry(QtCore.QRect(20, 280, 75, 23))
        self.cancelarCad.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cancelarCad.setObjectName("cancelarCad")
        self.limparCad = QtWidgets.QPushButton(Dialog)
        self.limparCad.setGeometry(QtCore.QRect(160, 280, 75, 23))
        self.limparCad.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.limparCad.setObjectName("limparCad")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Cadastro de Usuário</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Nome: </span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Usuário: </span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Senha:</span></p></body></html>"))
        self.gerarSenha.setText(_translate("Dialog", "Gerar Senha"))
        self.slavarCad.setText(_translate("Dialog", "Salvar"))
        self.cancelarCad.setText(_translate("Dialog", "Cancelar"))
        self.limparCad.setText(_translate("Dialog", "Limpar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Cadastro()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
