# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(384, 240)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 0, 261, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(54, 88, 71, 21))
        self.label_2.setObjectName("label_2")
        self.Entrar = QtWidgets.QPushButton(Dialog)
        self.Entrar.setGeometry(QtCore.QRect(100, 180, 75, 23))
        self.Entrar.setObjectName("Entrar")
        self.Cancelar = QtWidgets.QPushButton(Dialog)
        self.Cancelar.setGeometry(QtCore.QRect(220, 180, 75, 23))
        self.Cancelar.setObjectName("Cancelar")
        self.usuairo = QtWidgets.QLineEdit(Dialog)
        self.usuairo.setGeometry(QtCore.QRect(120, 90, 171, 21))
        self.usuairo.setObjectName("usuairo")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(55, 118, 81, 21))
        self.label_5.setObjectName("label_5")
        self.senha = QtWidgets.QLineEdit(Dialog)
        self.senha.setGeometry(QtCore.QRect(120, 120, 171, 21))
        self.senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha.setObjectName("senha")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 391, 241))
        self.label_3.setStyleSheet("background-color: rgb(173, 173, 173);")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.Entrar.raise_()
        self.Cancelar.raise_()
        self.usuairo.raise_()
        self.label_5.raise_()
        self.senha.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Gerenciador de Senha</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Usuario:</span></p></body></html>"))
        self.Entrar.setText(_translate("Dialog", "Entrar"))
        self.Cancelar.setText(_translate("Dialog", "Cancelar"))
        self.usuairo.setPlaceholderText(_translate("Dialog", "Usúairo"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Sennha:</span></p></body></html>"))
        self.senha.setPlaceholderText(_translate("Dialog", "Senha"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
