# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1273, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 16, 901, 41))
        self.label.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 1221, 490))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(187)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.verticalHeader().setMinimumSectionSize(23)
        self.pesquisa = QtWidgets.QLineEdit(self.centralwidget)
        self.pesquisa.setGeometry(QtCore.QRect(920, 19, 270, 34))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pesquisa.setFont(font)
        self.pesquisa.setText("")
        self.pesquisa.setObjectName("pesquisa")
        self.btnPesquisa = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesquisa.setGeometry(QtCore.QRect(1200, 21, 28, 31))
        self.btnPesquisa.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    image: url(:/img/magnify.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    image: url(:/img/magnify (1).png);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.btnPesquisa.setText("")
        self.btnPesquisa.setObjectName("btnPesquisa")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionCadastrar = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/account-multiple-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar.setIcon(icon)
        self.actionCadastrar.setObjectName("actionCadastrar")
        self.actionEditar = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/account-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditar.setIcon(icon1)
        self.actionEditar.setObjectName("actionEditar")
        self.actionExcluir = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExcluir.setIcon(icon2)
        self.actionExcluir.setObjectName("actionExcluir")
        self.actionSair = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/door-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSair.setIcon(icon3)
        self.actionSair.setObjectName("actionSair")
        self.toolBar.addAction(self.actionCadastrar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEditar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExcluir)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSair)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Usuários Recentes</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Usuário"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Senha Anterior"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sneha Atual"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.actionCadastrar.setToolTip(_translate("MainWindow", "Cadastrar Uusário"))
        self.actionEditar.setText(_translate("MainWindow", "Editar"))
        self.actionEditar.setToolTip(_translate("MainWindow", "Editar Usuário"))
        self.actionExcluir.setText(_translate("MainWindow", "Excluir"))
        self.actionExcluir.setToolTip(_translate("MainWindow", "Excluir Usuário"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSair.setToolTip(_translate("MainWindow", "Sair"))
import templates.imgMenu


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
